export const ExpenseActionTypes = {
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  GET_EXPENSES: 'GET_EXPENSES',
  DO_ADD_EXPENSES: 'DO_ADD_EXPENSES',
  DO_UPDATE_EXPENSES: 'DO_UPDATE_EXPENSES',
};
