export default {
  appName: 'Liq stocks',
  englishLang: 'English',
  hindiLang: 'हिंदी',
  selectLanguage: 'Select Language',
  language: 'Language',
  currencySymbol: '₹',
  priceWithCurrency: '₹%{price}',
  dashboardTabName: 'Dashboard',
  itemsTabName: 'Items',
  inventoryTabName: 'Inventory',
  expenseTabName: 'Expense',
  reportTabName: 'Reports',
  salesTabName: 'Sales',
  commissionTabName: 'Commission',
  welcome: 'Welcome!',
  loginSignup: 'Log in or sign up',
  continue: 'Continue',
  mobilePlaceholder: 'Enter Mobile number',
  otpVerification: 'OTP Verification',
  descriptionText: 'An 4 digit code has sent to\n%{mobileNumber}',
  verify: 'Verify',
  signUpDescription: 'Tell us few more details about you',
  storeName: 'Store name',
  ownerName: 'Owner name',
  firstName: 'Your first name',
  lastName: 'Your last name',
  referralCode: 'Referral code',
  resend: 'Resend OTP',
  planDescription: 'Choose your\nsubscription plan',
  planDescriptionText: 'Create an account to get started',
  yearly: 'Yearly',
  salesman: 'Add upto %{noOfSalesman} Salesman',
  everyYear: 'every year',
  manageItemTips: 'Easy to Manage your Item',
  manageInventoryTips: 'Easy to Manage your Inventory',
  manageExpenseTips: 'Easy to Manage your Expense',
  manageSalesreportTips: 'Easy to Check your sales reports',
  freetrialDays: '%{noOfDays}-Day free trial',
  emptyMobile: 'Please enter mobile number.',
  invalidMobile: 'Please enter valid mobile number.',
  emptyOtp: 'Please enter otp',
  gotoDashboard: 'Go on Dashboard',
  helloUserText: 'Hi, %{username}\nCongratulation',
  successText: 'You have successfully registered',
  bhejan_menu: 'Bhejan',
  receivable_menu: 'Arrival',
  addReceivable: 'Add Arrival',

  myProfile_menu: 'My Profile',
  salesman_menu: 'Salesman',
  wallet_menu: 'Wallet',
  refer_a_friend_menu: 'Refer a friend',
  redeem_request: 'Redeem request',
  logout_menu: 'Logout',
  menu_header_text: 'Menu',
  logoutText: 'Do you want to logout?',
  deleteText: 'Do you want to delete account?',
  totalSales: 'Total Sales',
  totalExpens: 'Total Expenses',
  totalCollection: 'Total Collections',
  totalCommission: 'Total Commission',
  today: 'Today',
  allTime: 'All Time',
  deleteAccount: 'Delete Account',
  editProfile: 'Edit Profile',
  noItemTitle: 'No %{tabName} added',
  noItemAddText:
    'Hi, You have not added any %{tabName}\ntill yet, so please click on add\nbutton and add your %{tabName}.',
  noWalletAddText:
    'Hi, You have not added any record\ntill yet, so please click on Refer\na friend button and create your money.',

  cancel: 'Cancel',
  update: 'Update',
  yourStoreName: 'Store Name',
  yourFirstName: 'Your First Name',
  yourLastName: 'Your Last Name',
  save: 'Save',
  productName: 'Product name',
  fullPrice: 'Full price',
  halfPrice: 'Half price',
  quaterPrice: 'Quater price',
  category: 'Select category',
  subCategory: 'Select sub category',
  selectExpense: 'Select Expense type',
  addItems: 'Add Item',
  addSales: 'Add Sales',
  addBhejan: 'Add Bhejan',
  addCommission: 'Add Commission',
  addInventory: 'Add Inventory',
  addExpense: 'Add Expense',
  itemType: 'Item Type',
  fullType: 'Full',
  halfType: 'Half',
  quaterType: 'Quater',
  selectCategoryError: 'Please select category.',
  selectSubCategoryError: 'Please select sub category.',
  productNameError: 'Please enter product name.',
  fullPriceError: 'Please enter full price.',
  halfPriceError: 'Please enter half price.',
  quaterPriceError: 'Please enter quater price.',
  itemTypeError: 'Please select item type.',
  enterPriceError: 'Please enter %{type} price.',
  enterZeroPriceError: '%{type} price can’t be 0.',
  enterZeroQuantityError: '%{type} quantity can’t be 0.',
  enterEmptyRemarkError: '%{type} remark can’t be empty.',
  bheajnRemarkPlaceholder: 'Enter Remark',
  enterPrice: '₹ %{type} price',
  enterType: 'Enter %{type}',
  typePrice: '%{type} price',
  search: 'search here',
  apply: 'Apply',
  bottleQuantity: '%{type} bottle quantity',
  enterQuantity: `Enter %{type} bottle quantity`,
  expenseName: 'Expense Name',
  expenseNamePlaceholder: 'Enter Expense Name',
  expenseNameError: 'Please enter expense name.',
  expenseAmount: '₹ Amount',
  redeemAmount: '₹ Amount',
  expenseAmountPlaceholder: 'Enter Expense Amount(₹)',
  expenseAmountError: 'Please enter expense amount.',
  expenseRemark: 'Add Remark',
  expenseRemarkPlaceholder: 'Enter Expense Remark',
  expenseRemarkError: 'Please enter expense remark.',
  selectExpenseError: 'Please select Expense type.',
  enterQauntityError: 'Please enter %{type} bottle quantity.',
  noReportText: 'Hi, You have not any %{tabName} till yet.',
  typeAmount: '%{type} Amount',
  firstNameSales: 'First Name',
  lastNameSales: 'Last Name',
  mobileNumber: 'Mobile Number',
  commonPlaceholder: 'Enter %{label}',
  commonEmptyError: 'Please enter %{label}.',
  addSalesman: 'Add Salesman',
  upiId: 'UPI ID',
  inviteFriendAmount: 'Invite friends to get %{price}',
  referalLabel: 'Referal code',
  referalCode: '#%{code}',
  shareWithAFriend: 'Share with a friend',
  inviteFriendAmountDesc:
    'Invite friends to Liq Stocks and get %{price} in your wallet on their first purchase of service.',
  selectProductName: 'Select product name',
  selectProductError: 'Please select product.',
  quantity: 'Quantity',
  commission: 'Commission',
  initialtext: 'Initial',
  regularText: 'Regular',
  searchTitle: 'Search',
  typeBottleQuantity: '%{type} bottle quantity',
  typeBottleCommission: '₹%{type} bottle commission Amount',
  errorBottleCommission: 'Please enter %{type} bottle commission.',
  enterBottleCommission: '₹ %{type} bottle commission',
  errorBottleQuantity: 'Please enter %{type} bottle quantity.',
  enterBottleQuantity: '%{type} bottle quantity',
  deleteUserAsk: 'Do you want to delete this user?',
  accountDeleteInfo:
    'Your account is deleted please contact to admin for further info.',
  filterTitle: 'Filter',
  addedOn: 'Added on %{date}',
  langChangeText: 'Do you want to chnage language?',
  yesText: 'Yes',
  noText: 'No',
  okText: 'OK',
  restartApp: 'Please restart the application to see updated language.',
  totalPrice: '₹%{price}',
  appleStore: 'Apple store\nLink:- %{url}',
  googleStore: 'Google Play Store\nLink:- %{url}',
  invalidUpi: 'UPI Id is invalid.',
  shareMsgLink:
    "Here's your referal link\nReady to install?\n1. Downlaod the Liq Stocks from %{type}\n2. Create an account with this %{referal} Referral code.",
  name: 'Name',
};
