export default {
  appName: 'Liq Stocks',
  currencySymbol: '$',
  dashboardTabName: 'Dashboard',
  itemsTabName: 'Items',
  inventoryTabName: 'Inventory',
  expenseTabName: 'Expense',
  reportTabName: 'Reports',
  welcome: 'Welcome!',
  loginSignup: 'Log in or sign up',
  continue: 'Continue',
  mobilePlaceholder: 'Enter Mobile number',
  otpVerification: 'OTP Verification',
  descriptionText: 'An 4 digit code has sent to\n%{mobileNumber}',
  verify: 'Verify',
  signUpDescription: 'Tell us few more details about you',
  storeName: 'Store name',
  firstName: 'Your first name',
  lastName: 'Your last name',
  referralCode: 'Referral code',
  resend: 'Resend OTP',
  planDescription: 'Choose your\nsubscription plan',
  planDescriptionText: 'Create an account to get started',
  yearly: 'Yearly',
  salesman: 'Add upto %{noOfSalesman} Salesman',
  everyYear: 'every year',
  manageItemTips: 'Easy to Manage your Item',
  manageInventoryTips: 'Easy to Manage your Inventory',
  manageExpenseTips: 'Easy to Manage your Expense',
  manageSalesreportTips: 'Easy to Check your sales reports',
  freetrialDays: '%{noOfDays}-Day free trial',
  emptyMobile: 'Please enter mobile number.',
  invalidMobile: 'Please enter valid mobile number.',
  emptyOtp: 'Please enter otp',
  gotoDashboard: 'Go on Dashboard',
  helloUserText: 'Hi, %{username}\nCongratulation',
  successText: 'You have successfully registered',
};
