export default {
  appName: 'Liq Stocks',
  currencySymbol: '$',
  dashboardTabName: 'Dashboard',
  itemsTabName: 'Items',
  inventoryTabName: 'Inventory',
  expenseTabName: 'Expense',
  reportTabName: 'Reports',
  welcome: 'Welcome!',
  loginSignup: 'Log in or sign up',
  continue: 'Continue',
  mobilePlaceholder: 'Enter Mobile number',
  otpVerification: 'OTP Verification',
  descriptionText: 'An 4 digit code has sent to\n%{mobileNumber}',
  verify: 'Verify',
  signUpDescription: 'Tell us few more details about you',
  storeName: 'Store name',
  firstName: 'Your first name',
  lastName: 'Your last name',
  referralCode: 'Referral code',
};
