export default {
  appName: 'Liq stocks',
  selectLanguage: 'भाषा चुने',
  englishLang: 'English',
  language: 'भाषा',
  hindiLang: 'हिंदी',
  currencySymbol: '₹',
  priceWithCurrency: '₹%{price}',
  dashboardTabName: 'Dashboard',
  itemsTabName: 'Items',
  inventoryTabName: 'Inventory',
  expenseTabName: 'Expense',
  reportTabName: 'Reports',
  salesTabName: 'Sales',
  commissionTabName: 'Commission',
  welcome: 'स्वागत!',
  loginSignup: 'लॉग इन या साइन अप',
  continue: 'जारी रखना',
  mobilePlaceholder: 'मोबाइल नंबर दर्ज करें',
  otpVerification: 'ओटीपी सत्यापन',
  descriptionText: 'मोबाइल नंबर %{mobileNumber} पर 4 अंकों\nका कोड भेजा गया है',
  verify: 'सत्यापित करें',
  signUpDescription: 'हमें अपने बारे में कुछ और विवरण बताएं',
  storeName: 'स्टोर नाम',
  ownerName: 'मालिक का नाम',
  firstName: 'आपका प्रथम नाम',
  lastName: 'आपका अंतिम नाम',
  referralCode: 'रेफरल कोड',
  resend: 'ओटीपी पुनः भेजें',
  planDescription: 'अपनी सदस्यता\nयोजना चुनें',
  planDescriptionText: 'आरंभ करने के लिए एक खाता बनाएँ',
  yearly: 'सालाना',
  salesman: '%{noOfSalesman} सेल्समैन तक जोड़ें',
  everyYear: 'प्रत्येक वर्ष',
  manageItemTips: 'अपने आइटम को प्रबंधित करना आसान है',
  manageInventoryTips: 'अपनी इन्वेंटरी को प्रबंधित करना आसान है',
  manageExpenseTips: 'अपने व्यय का प्रबंधन करना आसान',
  manageSalesreportTips: 'अपनी बिक्री रिपोर्ट की जांच करना आसान है',
  freetrialDays: '%{noOfDays}-दिन नि: शुल्क परीक्षण',
  emptyMobile: 'कृपया मोबाइल नंबर दर्ज करें.',
  invalidMobile: 'कृपया मान्य मोबाइल नंबर दर्ज करें.',
  emptyOtp: 'कृपया ओटीपी दर्ज करें',
  gotoDashboard: 'Go on Dashboard',
  helloUserText: 'नमस्ते, %{username}\nबधाई',
  successText: 'आपको सफलतापूर्वक रजिस्टर कर लिया है',
  bhejan_menu: 'Bhejan',
  myProfile_menu: 'My Profile',
  salesman_menu: 'Salesman',
  wallet_menu: 'Wallet',
  refer_a_friend_menu: 'Refer a friend',
  redeem_request: 'Redeem request',
  logout_menu: 'Logout',
  menu_header_text: 'Menu',
  logoutText: 'क्या आप लॉगआउट करना चाहते हैं?',
  deleteText: 'क्या आप खाता हटाना चाहते हैं?',
  totalSales: 'Total Sales',
  totalExpens: 'Total Expenses',
  totalCollection: 'Total Collections',
  totalCommission: 'Total Commission',
  today: 'आज',
  allTime: 'All Time',
  deleteAccount: 'Delete Account',
  editProfile: 'Edit Profile',
  noItemTitle: 'No %{tabName} added',
  noItemAddText:
    'Hi, You have not added any %{tabName}\ntill yet, so please click on add\nbutton and add your %{tabName}.',
  cancel: 'Cancel',
  update: 'Update',
  yourStoreName: 'Store Name',
  yourFirstName: 'Your First Name',
  yourLastName: 'Your Last Name',
  save: 'Save',
  productName: 'Product name',
  fullPrice: 'Full price',
  halfPrice: 'Half price',
  quaterPrice: 'Quater price',
  category: 'Select category',
  subCategory: 'Select sub category',
  selectExpense: 'Select Expense type',
  addItems: 'Add Item',
  addSales: 'Add Sales',
  addBhejan: 'Add Bhejan',
  addCommission: 'Add Commission',
  addInventory: 'Add Inventory',
  addExpense: 'Add Expense',
  itemType: 'Item Type',
  fullType: 'Full',
  halfType: 'Half',
  quaterType: 'Quater',
  selectCategoryError: 'Please select category.',
  selectSubCategoryError: 'Please select sub category.',
  productNameError: 'Please enter product name.',
  fullPriceError: 'Please enter full price.',
  halfPriceError: 'Please enter half price.',
  quaterPriceError: 'Please enter quater price.',
  itemTypeError: 'Please select item type.',
  enterPriceError: 'Please enter %{type} price.',
  enterZeroPriceError: '%{type} price can’t be 0.',
  enterZeroQuantityError: '%{type} quantity can’t be 0.',
  enterPrice: '₹ %{type} price',
  enterType: 'Enter %{type}',
  typePrice: '%{type} price',
  search: 'search here',
  apply: 'Apply',
  bottleQuantity: '%{type} bottle quantity',
  enterQuantity: `Enter %{type} bottle quantity`,
  expenseName: 'Expense Name',
  expenseNamePlaceholder: 'Enter Expense Name',
  expenseNameError: 'Please enter expense name.',
  expenseAmount: '₹ Amount',
  redeemAmount: '₹ Amount',
  expenseAmountPlaceholder: 'Enter Expense Amount(₹)',
  expenseAmountError: 'Please enter expense amount.',
  expenseRemark: 'Add Remark',
  expenseRemarkPlaceholder: 'Enter Expense Remark',
  expenseRemarkError: 'Please enter expense remark.',
  selectExpenseError: 'Please select Expense type.',
  enterQauntityError: 'Please enter %{type} bottle quantity.',
  noReportText: 'Hi, You have not any %{tabName} till yet.',
  typeAmount: '%{type} Amount',
  firstNameSales: 'First Name',
  lastNameSales: 'Last Name',
  mobileNumber: 'Mobile Number',
  commonPlaceholder: 'Enter %{label}',
  commonEmptyError: 'Please enter %{label}.',
  addSalesman: 'Add Salesman',
  upiId: 'UPI ID',
  inviteFriendAmount: 'Invite friends to get %{price}',
  referalLabel: 'Referal code',
  referalCode: '#%{code}',
  shareWithAFriend: 'Share with a friend',
  inviteFriendAmountDesc:
    'Invite friends to Liq Stocks and get %{price} in your wallet on their first purchase of service.',
  selectProductName: 'Select product name',
  selectProductError: 'Please select product.',
  quantity: 'Quantity',
  commission: 'Commission',
  initialtext: 'Initial',
  regularText: 'Regular',
  searchTitle: 'Search',
  typeBottleQuantity: '%{type} bottle quantity',
  typeBottleCommission: '₹%{type} bottle commission Amount',
  errorBottleCommission: 'Please enter %{type} bottle commission.',
  enterBottleCommission: '₹ %{type} bottle commission',
  errorBottleQuantity: 'Please enter %{type} bottle quantity.',
  enterBottleQuantity: '%{type} bottle quantity',
  deleteUserAsk: 'Do you want to delete this user?',
  accountDeleteInfo:
    'Your account is deleted please contact to admin for further info.',
  filterTitle: 'Filter',
  addedOn: 'Added on %{date}',
  langChangeText: 'क्या आप भाषा बदलना चाहते हैं?',
  yesText: 'हाँ',
  noText: 'नहीं',
  okText: 'ठीक',
  restartApp: 'अपडेट की गई भाषा देखने के लिए कृपया एप्लिकेशन को पुनरारंभ करें।',
};
