export default {
  appName: 'Liq stocks',
  selectLanguage: 'भाषा चुने',
  englishLang: 'English',
  language: 'भाषा',
  hindiLang: 'हिंदी',
  currencySymbol: '₹',
  priceWithCurrency: '₹%{price}',
  dashboardTabName: 'डैशबोर्ड',
  itemsTabName: 'सामान',
  inventoryTabName: 'सूची',
  expenseTabName: 'खर्चा',
  reportTabName: 'रिपोर्ट्स',
  salesTabName: 'बिक्री',
  commissionTabName: 'कमीशन',
  welcome: 'स्वागत!',
  loginSignup: 'लॉग इन या साइन अप',
  continue: 'जारी रखना',
  mobilePlaceholder: 'मोबाइल नंबर दर्ज करें',
  otpVerification: 'ओटीपी सत्यापन',
  descriptionText: 'मोबाइल नंबर %{mobileNumber} पर 4 अंकों\nका कोड भेजा गया है',
  verify: 'सत्यापित करें',
  signUpDescription: 'हमें अपने बारे में कुछ और विवरण बताएं',
  storeName: 'स्टोर नाम',
  ownerName: 'मालिक का नाम',
  firstName: 'आपका प्रथम नाम',
  lastName: 'आपका अंतिम नाम',
  referralCode: 'रेफरल कोड',
  resend: 'ओटीपी पुनः भेजें',
  planDescription: 'अपनी सदस्यता\nयोजना चुनें',
  planDescriptionText: 'आरंभ करने के लिए एक खाता बनाएँ',
  yearly: 'सालाना',
  salesman: '%{noOfSalesman} सेल्समैन तक जोड़ें',
  everyYear: 'प्रत्येक वर्ष',
  manageItemTips: 'अपने आइटम को प्रबंधित करना आसान है',
  manageInventoryTips: 'अपनी इन्वेंटरी को प्रबंधित करना आसान है',
  manageExpenseTips: 'अपने व्यय का प्रबंधन करना आसान',
  manageSalesreportTips: 'अपनी बिक्री रिपोर्ट की जांच करना आसान है',
  freetrialDays: '%{noOfDays}-दिन नि: शुल्क परीक्षण',
  emptyMobile: 'कृपया मोबाइल नंबर दर्ज करें.',
  invalidMobile: 'कृपया मान्य मोबाइल नंबर दर्ज करें.',
  emptyOtp: 'कृपया ओटीपी दर्ज करें',
  gotoDashboard: 'डैशबोर्ड पर जाएँ',
  helloUserText: 'नमस्ते, %{username}\nबधाई',
  successText: 'आपको सफलतापूर्वक रजिस्टर कर लिया है',
  bhejan_menu: 'भेजन',
  receivable_menu: 'आगमन',
  addReceivable: 'आगमन जोड़ें',
  myProfile_menu: 'प्रोफाइल',
  salesman_menu: 'विक्रेता',
  wallet_menu: 'पर्स',
  refer_a_friend_menu: 'मित्र को सूचित करें',
  redeem_request: 'रिडीम अनुरोध',
  logout_menu: 'लॉग आउट',
  menu_header_text: 'मेन्यू',
  logoutText: 'क्या आप लॉगआउट करना चाहते हैं?',
  deleteText: 'क्या आप खाता हटाना चाहते हैं?',
  totalSales: 'कुल बिक्री',
  totalExpens: 'कुल खर्च',
  totalCollection: 'कुल संग्रह',
  totalCommission: 'कुल कमीशन',
  today: 'आज',
  allTime: 'पूरे समय',
  deleteAccount: 'खाता हटाना',
  editProfile: 'प्रोफ़ाइल संपादित करें',
  noItemTitle: 'कोई %{tabName} नहीं जोड़ा गया',
  noItemAddText:
    'नमस्ते, आपने अभी तक कोई %{tabName}\nनहीं जोड़ा है, इसलिए कृपया ऐड\nबटन पर क्लिक करें और अपना %{tabName} जोड़ें।.',
  cancel: 'रद्द',
  update: 'अपडेट',
  yourStoreName: 'स्टोर नाम',
  yourFirstName: 'आपका प्रथम नाम',
  yourLastName: 'आपका उपनाम',
  save: 'रक्षित',
  productName: 'प्रोडक्ट का नाम',
  fullPrice: 'पूरी कीमत',
  halfPrice: 'आधी कीमत',
  quaterPrice: 'तिमाही कीमत',
  category: 'श्रेणी चुनें',
  subCategory: 'उप श्रेणी चुनें',
  selectExpense: 'खर्चा प्रकार चुनें',
  addItems: 'आइटम जोड़ें',
  addSales: 'बिक्री जोड़ें',
  addBhejan: 'भेजन जोड़ें',
  addCommission: 'कमीशन जोड़ें',
  addInventory: 'सूची जोड़ें',
  addExpense: 'खर्चा जोड़ें',
  itemType: 'वस्तु का प्रकार',
  fullType: 'फुल',
  halfType: 'आधा',
  quaterType: 'क्वाटर',
  selectCategoryError: 'कृपया श्रेणी चुनें',
  selectSubCategoryError: 'कृपया उप श्रेणी का चयन करें।',
  productNameError: 'कृपया उत्पाद का नाम दर्ज करें।',
  fullPriceError: 'कृपया फुल कीमत दर्ज करें।',
  halfPriceError: 'कृपया आधी कीमत दर्ज करें।',
  quaterPriceError: 'कृपया तिमाही कीमत दर्ज करें।',
  itemTypeError: 'कृपया आइटम प्रकार का चयन करें।',
  enterPriceError: 'कृपया %{type} कीमत दर्ज करें।',
  enterZeroPriceError: '%{type} कीमत 0 नहीं हो सकती।',
  enterZeroQuantityError: '%{type} मात्रा 0 नहीं हो सकती।',
  enterPrice: '₹ %{type} कीमत',
  enterType: '%{type} दर्ज करें',
  typePrice: '%{type} कीमत',
  search: 'यहाँ खोजें',
  apply: 'अप्लाई करें',
  bottleQuantity: '%{type} बोतल मात्रा',
  enterQuantity: `%{type} बोतल मात्रा दर्ज करें`,
  expenseName: 'खर्चा का नाम',
  expenseNamePlaceholder: 'खर्चा का नाम दर्ज करें',
  expenseNameError: 'कृपया खर्चा का नाम दर्ज करें.',
  expenseAmount: '₹ राशि',
  redeemAmount: '₹ राशि',
  expenseAmountPlaceholder: 'खर्च राशि(₹) ',
  expenseAmountError: 'खर्च राशि(₹) दर्ज करें.',
  expenseRemark: 'टिप्पणी जोड़ें',
  expenseRemarkPlaceholder: 'खर्च टिप्पणी',
  expenseRemarkError: 'कृपया खर्च टिप्पणी दर्ज करें।',
  selectExpenseError: 'कृपया खर्च प्रकार चुनें।',
  enterQauntityError: 'कृपया %{type} बोतल मात्रा दर्ज करें।',
  noReportText: 'नमस्ते, आपके पास अभी तक कोई %{tabName} नहीं है',
  typeAmount: '%{type} राशि',
  firstNameSales: 'पहला नाम',
  lastNameSales: 'उपनाम',
  mobileNumber: 'मोबाइल नंबर',
  commonPlaceholder: '%{label} दर्ज',
  commonEmptyError: 'कृपया %{label} दर्ज करें।',
  addSalesman: 'सेल्समैन जोड़ें',
  upiId: 'यूपीआई आईडी',
  inviteFriendAmount: '%{price} प्राप्त करने के लिए मित्रों को आमंत्रित करें',
  referalLabel: 'रेफरल कोड',
  referalCode: '#%{code}',
  shareWithAFriend: 'दोस्त के साथ साझा करें',
  inviteFriendAmountDesc:
    'दोस्तों को Liq Stocks में आमंत्रित करें और उनकी पहली सेवा खरीद पर अपने वॉलेट में ₹ %{price} प्राप्त करें',
  selectProductName: 'उत्पाद का नाम चुनें',
  selectProductError: 'कृपया उत्पाद का चयन करें.',
  quantity: 'मात्रा',
  commission: 'कमीशन',
  initialtext: 'प्रारंभिक',
  regularText: 'नियमित',
  searchTitle: 'खोजें',
  typeBottleQuantity: '%{type} बोतल मात्रा',
  typeBottleCommission: '₹%{type} बोतल कमीशन राशि',
  errorBottleCommission: '%{type} बोतल कमीशन दर्ज करें।',
  enterBottleCommission: '₹ %{type} बोतल कमीशन',
  errorBottleQuantity: '%{type} बोतल मात्रा दर्ज करें।',
  enterBottleQuantity: '%{type} बोतल मात्रा',
  deleteUserAsk: 'क्या आप इस यूजर को हटाना चाहते हैं?',
  accountDeleteInfo:
    'आपका खाता हटा दिया गया है कृपया अधिक जानकारी के लिए एडमिन से संपर्क करें।',
  filterTitle: 'फ़िल्टर',
  addedOn: '%{date} को जोड़ा गया',
  langChangeText: 'क्या आप भाषा बदलना चाहते हैं?',
  yesText: 'हाँ',
  noText: 'नहीं',
  okText: 'ठीक',
  restartApp: 'अपडेट की गई भाषा देखने के लिए कृपया एप्लिकेशन को पुनरारंभ करें।',
};
