export const InventoryActionTypes = {
  EDIT_INVENTORY: 'EDIT_INVENTORY',
  DELETE_INVENTORY: 'DELETE_INVENTORY',
  GET_INVENTORY: 'GET_INVENTORY',
  DO_ADD_INVENTORY: 'DO_ADD_INVENTORY',
  DO_UPDATE_INVENTORY: 'DO_UPDATE_INVENTORY',
};
