export const LoginActionTypes = {
  DO_LOGIN: 'DO_LOGIN',
  SAVE_BEARERTOKEN: 'SAVE_BEARERTOKEN',
  REMEBER_CREDS: 'REMEBER_CREDS',
  REMOVE_CREDS: 'REMOVE_CREDS',
  SAVE_DATA_REMEMBER: 'SAVE_DATA_REMEMBER',
  SAVE_DATA: 'SAVE_DATA',

  DO_GET_USER: 'DO_GET_USER',
  DO_VALIDATE_USER: 'DO_VALIDATE_USER',
  SAVE_USER: 'SAVE_USER',
  SAVE_SESSION_USER: 'SAVE_SESSION_USER',
  CLEAR_SESSION: 'CLEAR_SESSION',
};
