export const ItemActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  EDIT_ITEM: 'EDIT_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  GET_ITEMS: 'GET_ITEMS',
  DO_GET_CATEGORY: 'DO_GET_CATEGORY',
  DO_SAVE_CATEGORY: 'DO_SAVE_CATEGORY',
  DO_GET_SUB_CATEGORY: 'DO_GET_SUB_CATEGORY',
  DO_GET_CATEGORY_TYPE: 'DO_GET_CATEGORY_TYPE',
  DO_ADD_ITEM: 'DO_ADD_ITEM',
};
